# Generated by Django 4.2.11 on 2024-07-06 17:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('complent', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavors_Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inputs_Salables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inputs', to='maingigapizza.inputs')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('tel', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='maingigapizza.address')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SubCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_category', to='maingigapizza.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='Salables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('inputs', models.ManyToManyField(related_name='salables', through='maingigapizza.Inputs_Salables', to='maingigapizza.inputs')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='maingigapizza.subcategorys')),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('flavors', models.ManyToManyField(through='maingigapizza.Flavors_Pizzas', to='maingigapizza.salables')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=datetime.datetime(2024, 7, 6, 14, 29, 18, 128709))),
                ('delivery_time', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='maingigapizza.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.orders')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.pizzas')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.orders')),
                ('salable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.salables')),
            ],
        ),
        migrations.AddField(
            model_name='inputs_salables',
            name='salable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salable', to='maingigapizza.salables'),
        ),
        migrations.AddField(
            model_name='flavors_pizzas',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pizza', to='maingigapizza.pizzas'),
        ),
        migrations.AddField(
            model_name='flavors_pizzas',
            name='salable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salablePizza', to='maingigapizza.salables'),
        ),
    ]
