# Generated by Django 4.2.11 on 2024-03-14 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlavorPizza',
            new_name='FlavorsPizza',
        ),
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Pizzas',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=datetime.datetime(2024, 3, 14, 15, 33, 59, 541013))),
                ('delivery_time', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='maingigapizza.users')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitens',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.orders'),
        ),
        migrations.AlterField(
            model_name='orderpizzas',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.orders'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
