# Generated by Django 4.2.11 on 2024-03-14 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0002_rename_flavorpizza_flavorspizza_rename_pizza_pizzas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 57, 8, 772074)),
        ),
    ]
