# Generated by Django 4.2.11 on 2024-07-08 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0003_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 14, 12, 46, 633689)),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
