# Generated by Django 4.2.11 on 2024-07-08 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0004_alter_orders_request_time_alter_users_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs_salables',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='input', to='maingigapizza.inputs'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 14, 27, 32, 190406)),
        ),
    ]
