# Generated by Django 4.2.11 on 2024-07-08 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0005_alter_inputs_salables_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs_salables',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.inputs'),
        ),
        migrations.AlterField(
            model_name='inputs_salables',
            name='salable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maingigapizza.salables'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 14, 31, 34, 620905)),
        ),
    ]
