# Generated by Django 4.2.11 on 2024-07-08 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0008_rename_input_inputs_salables_input_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputs_salables',
            old_name='input_id',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='inputs_salables',
            old_name='salable_id',
            new_name='salable',
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 15, 21, 39, 977811)),
        ),
    ]
