# Generated by Django 4.2.11 on 2024-07-08 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0009_rename_input_id_inputs_salables_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salables',
            name='inputs',
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 15, 27, 42, 179914)),
        ),
    ]
