# Generated by Django 4.2.11 on 2024-07-10 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0010_remove_salables_inputs_alter_orders_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilo'), ('g', 'Gramas'), ('l', 'Litro'), ('ml', 'Mililitro'), ('und', 'Unidade')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 23, 46, 42, 722423)),
        ),
    ]
