# Generated by Django 4.2.11 on 2024-07-10 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0011_alter_inputs_unit_alter_orders_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilo'), ('g', 'Gram'), ('mg', 'Miligram'), ('l', 'Liter'), ('ml', 'Mililiter'), ('und', 'Unit')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 23, 57, 53, 959489)),
        ),
    ]
