# Generated by Django 4.2.11 on 2024-07-10 03:32

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maingigapizza", "0015_alter_inputs_unit_alter_orders_request_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputs",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_inputs_subcategory",
                to="maingigapizza.subcategorys",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="request_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 10, 0, 32, 34, 138767)
            ),
        ),
    ]
