# Generated by Django 4.2.14 on 2024-07-15 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0017_rename_inputs_salables_salables_compositions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 20, 39, 39, 135595)),
        ),
        migrations.AddConstraint(
            model_name='salables_compositions',
            constraint=models.UniqueConstraint(fields=('salable', 'input'), name='unique_salable_composition_input_constraint'),
        ),
    ]
