# Generated by Django 4.2.14 on 2024-07-25 18:31

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maingigapizza", "0018_alter_orders_request_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Categorys",
        ),
        migrations.AlterField(
            model_name="orders",
            name="request_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 25, 15, 31, 7, 730607)
            ),
        ),
        migrations.AlterField(
            model_name="subcategorys",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="principal_category",
                to="maingigapizza.categories",
            ),
        ),
        migrations.RenameModel(
            old_name="SubCategorys",
            new_name="SubCategories",
        ),
        migrations.AddField(
            model_name="categories",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_category",
                to="maingigapizza.categorytypes",
            ),
        ),
        migrations.AlterField(
            model_name="subcategories",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="principal_category",
                to="maingigapizza.categories",
            ),
        ),
    ]
