# Generated by Django 4.2.14 on 2024-07-25 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0019_categories_categorytypes_delete_categorys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 15, 48, 44, 907965)),
        ),
    ]
