# Generated by Django 4.2.14 on 2024-07-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingigapizza', '0020_alter_orders_request_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inputs',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='salables',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='inputs',
            constraint=models.UniqueConstraint(fields=('name', 'subcategory'), name='unique_name_subcategory_in_inputs_constraint'),
        ),
        migrations.AddConstraint(
            model_name='salables',
            constraint=models.UniqueConstraint(fields=('name', 'subcategory'), name='unique_name_subcategory_in_salables_constraint'),
        ),
        migrations.AddConstraint(
            model_name='subcategories',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category_constraint'),
        ),
    ]
